import { useTranslation } from 'react-i18next';

const ko = {
  helpTitle: '도움말', basicGuide: '앱 사용 가이드', basicGuideDetail: '주요 기능을 다시 확인해요', widgetHowTo: '위젯 사용 방법', widgetHowToDetail: '즐겨찾기를 홈 화면에서도',
  skip: '건너뛰기', close: '닫기', previous: '이전', next: '다음', start: '시작하기', done: '확인', later: '나중에', revisit: '설정에서 언제든 다시 볼 수 있어요.',
  titles: ['안녕하세요!\n몇번이야? 입니다 👋', '번호를 몰라도 괜찮아요\n상황으로 바로 검색해보세요.', '가까운 응급실도\n지금 위치에서 바로.', '자주 쓰는 번호는\n즐겨찾기와 위젯으로.'],
  descriptions: ['필요한 순간,\n필요한 번호를 더 빠르게\n찾을 수 있어요.', '기관명이나 전화번호를 몰라도\n일상 속 상황을 입력하면\n관련 번호를 찾아드려요.', '현재 위치를 이용해 주변 응급의료기관을\n지도와 목록에서 확인할 수 있어요.', '즐겨찾기에 저장하면\n홈 화면 위젯에서도\n더 빠르게 사용할 수 있어요.'],
  favoritesTitle: '자주 쓰는 번호는\n즐겨찾기로.', favoritesBody: '자주 쓰는 번호에 별을 눌러보세요.\n즐겨찾기에서 빠르게 찾을 수 있어요.',
  widgetHint: '홈 화면 위젯', widgetPreviewNote: '앱 설치 후에는 홈 화면 위젯에서도 바로 걸 수 있어요.',
  privacy: '위치는 주변 응급실 검색에만 사용하며 앱에 저장하지 않아요.', search: '차가 고장났어요', chips: ['카드 분실', '교통사고', '보이스피싱'], nearby: '내 주변 응급실', map: '지도 · 전화 · 길찾기', favorites: '즐겨찾기', fire: '화재·구급', police: '범죄·경찰 신고',
  saved: '즐겨찾기에 저장했어요!', savedBody: '홈 화면에 위젯을 추가하면\n앱을 열지 않고도 즐겨찾기 번호로\n바로 전화할 수 있어요.', howToTitle: '홈 화면에 위젯 추가하기',
  iosSteps: ['홈 화면의 빈 공간을 길게 눌러주세요.', '편집 → 위젯 추가를 선택하세요.', '몇번이야?를 검색하세요.', '작게 · 중간 · 크게 중 원하는 크기를 선택하세요.', '위젯 추가를 눌러주세요.'],
  androidSteps: ['홈 화면의 빈 공간을 길게 눌러주세요.', '위젯을 선택하세요.', '몇번이야?를 찾아주세요.', '즐겨찾기 전화 위젯을 홈 화면에 추가하세요.', '원하는 크기로 조절할 수 있어요.'],
  menuNote: '기기 또는 홈 화면 앱에 따라 메뉴 이름이 조금 다를 수 있어요.', locationBody: '현재 위치를 이용해\n가까운 응급의료기관을 찾아드려요.', checks: ['위치는 주변 응급실 검색에만 사용해요.', '위치 기록을 앱에 저장하지 않아요.'], notNow: '지금은 안 할래요', find: '주변 응급실 찾기', page: (n: number) => `4개 중 ${n}번째 안내`,
};
type GuideCopy = typeof ko;
const en: GuideCopy = {
  helpTitle: 'Help', basicGuide: 'App guide', basicGuideDetail: 'Explore the main features', widgetHowTo: 'Widget guide', widgetHowToDetail: 'Favorites on your Home Screen', skip: 'Skip', close: 'Close', previous: 'Back', next: 'Next', start: 'Get started', done: 'Done', later: 'Later', revisit: 'You can revisit this guide in Settings.',
  titles: ['Hello!\nWelcome to WhatNumber 👋', 'No number? No problem.\nSearch by situation.', 'Nearby emergency rooms,\nfrom your location.', 'Keep useful numbers\nin favorites and widgets.'], descriptions: ['Find the number you need,\nwhen you need it.', 'Describe an everyday situation\nto find related numbers, even if you\ndo not know the organization.', 'Use your location to view nearby emergency medical facilities on a map and in a list.', 'Save a favorite to access it\nmore quickly from a\nHome Screen widget.'], favoritesTitle: 'Keep useful numbers\nin favorites.', favoritesBody: 'Tap the star beside a number.\nFind it quickly in your favorites.', widgetHint: 'Home Screen widget', widgetPreviewNote: 'After installing the app, you can also call from a Home Screen widget.', privacy: 'Location is used only for nearby emergency searches and is not saved in the app.', search: 'My car broke down', chips: ['Lost card', 'Traffic accident', 'Voice phishing'], nearby: 'Nearby emergency rooms', map: 'Map · Call · Directions', favorites: 'Favorites', fire: 'Fire & rescue', police: 'Police', saved: 'Saved to favorites!', savedBody: 'Add a Home Screen widget to call\nyour favorites without opening the app.', howToTitle: 'Add a Home Screen widget', iosSteps: ['Touch and hold an empty area of the Home Screen.', 'Choose Edit → Add Widget.', 'Search for 몇번이야?.', 'Choose a small, medium, or large widget.', 'Tap Add Widget.'], androidSteps: ['Touch and hold an empty area of the Home Screen.', 'Choose Widgets.', 'Find 몇번이야?.', 'Add the 즐겨찾기 전화 widget to your Home Screen.', 'Resize the widget as you like.'], menuNote: 'Menu names may vary by device or launcher.', locationBody: 'Use your current location to find\nnearby emergency medical facilities.', checks: ['Location is used only for nearby emergency searches.', 'Location history is not saved in the app.'], notNow: 'Not now', find: 'Find nearby ERs', page: (n) => `Guide ${n} of 4`,
};
const ja: GuideCopy = { ...en, helpTitle: 'ヘルプ', basicGuide: 'アプリの使い方', basicGuideDetail: '主な機能を確認', widgetHowTo: 'ウィジェットの使い方', widgetHowToDetail: 'ホーム画面でもお気に入りを', skip: 'スキップ', close: '閉じる', previous: '戻る', next: '次へ', start: 'はじめる', done: '確認', later: 'あとで', revisit: '設定からいつでも見直せます。', titles: ['こんにちは！\n몇번이야? です 👋', '番号がわからなくても\n状況から検索できます。', '近くの救急医療機関を\n現在地から。', 'よく使う番号は\nお気に入りとウィジェットへ。'], descriptions: ['必要なときに、\n必要な番号をすばやく\n見つけられます。', '機関名や電話番号がわからなくても、\n状況を入力すると\n関連する番号が見つかります。', '現在地を使い、近くの救急医療機関を\n地図と一覧で確認できます。', 'お気に入りに保存すると、\nホーム画面のウィジェットでも\nすばやく使えます。'], favoritesTitle: 'よく使う番号は\nお気に入りへ。', favoritesBody: '番号の星をタップすると、\nお気に入りからすぐに見つかります。', widgetHint: 'ホーム画面ウィジェット', widgetPreviewNote: 'アプリをインストールすると、ホーム画面ウィジェットからもすぐ使えます。', privacy: '位置情報は周辺の救急医療機関の検索にのみ使い、アプリには保存しません。', search: '車が故障しました', chips: ['カード紛失', '交通事故', '電話詐欺'], nearby: '周辺の救急医療機関', map: '地図・電話・経路', favorites: 'お気に入り', fire: '消防・救助', police: '警察', saved: 'お気に入りに保存しました！', savedBody: 'ホーム画面にウィジェットを追加すると、\nアプリを開かなくてもお気に入り番号に\nすぐ電話できます。', howToTitle: 'ホーム画面にウィジェットを追加', iosSteps: ['ホーム画面の空いている場所を長押しします。', '編集 → ウィジェットを追加を選びます。', '몇번이야? を検索します。', '小・中・大からサイズを選びます。', 'ウィジェットを追加をタップします。'], androidSteps: ['ホーム画面の空いている場所を長押しします。', 'ウィジェットを選びます。', '몇번이야? を探します。', '즐겨찾기 전화 をホーム画面に追加します。', 'お好みのサイズに調整できます。'], menuNote: '機種やホームアプリによってメニュー名が異なる場合があります。', locationBody: '現在地を利用して、\n近くの救急医療機関を探します。', checks: ['位置情報は周辺の救急医療機関の検索にのみ使います。', '位置履歴をアプリに保存しません。'], notNow: '今はしない', find: '周辺の救急医療機関を探す', page: (n) => `全4ページ中${n}ページ目` };
const zh: GuideCopy = { ...en, helpTitle: '帮助', basicGuide: '应用使用指南', basicGuideDetail: '了解主要功能', widgetHowTo: '小组件使用指南', widgetHowToDetail: '在主屏幕使用收藏号码', skip: '跳过', close: '关闭', previous: '上一步', next: '下一步', start: '开始使用', done: '确定', later: '稍后', revisit: '可随时在设置中再次查看。', titles: ['您好！\n欢迎使用 몇번이야? 👋', '不知道号码也没关系\n按场景搜索即可。', '从当前位置\n查找附近急诊机构。', '常用号码\n收藏到小组件中。'], descriptions: ['在需要时，\n更快找到\n需要的号码。', '不清楚机构名称或电话号码也没关系，\n输入日常场景，\n即可找到相关号码。', '使用当前位置，\n在地图和列表中查看附近急诊机构。', '保存到收藏后，\n也可通过主屏幕小组件\n更快使用。'], favoritesTitle: '将常用号码\n加入收藏。', favoritesBody: '点击号码旁的星标，\n即可在收藏中快速找到。', widgetHint: '主屏幕小组件', widgetPreviewNote: '安装正式版应用后，也可通过主屏幕小组件快速拨打。', privacy: '位置信息仅用于查找附近急诊机构，不会保存在应用中。', search: '车坏了', chips: ['银行卡丢失', '交通事故', '电话诈骗'], nearby: '附近急诊机构', map: '地图 · 电话 · 路线', favorites: '收藏', fire: '消防·救援', police: '报警', saved: '已加入收藏！', savedBody: '添加主屏幕小组件后，\n无需打开应用也能\n直接拨打收藏号码。', howToTitle: '添加主屏幕小组件', iosSteps: ['长按主屏幕空白处。', '选择编辑 → 添加小组件。', '搜索 몇번이야?。', '选择小、中或大尺寸。', '点击添加小组件。'], androidSteps: ['长按主屏幕空白处。', '选择小组件。', '找到 몇번이야?。', '将 즐겨찾기 전화 添加到主屏幕。', '可按需要调整大小。'], menuNote: '菜单名称可能因设备或桌面应用而异。', locationBody: '使用当前位置，\n查找附近急诊医疗机构。', checks: ['位置信息仅用于搜索附近急诊机构。', '位置记录不会保存在应用中。'], notNow: '暂时不用', find: '查找附近急诊机构', page: (n) => `第${n}页，共4页` };
export function getGuideCopy(language: string): GuideCopy { return language.startsWith('ko') ? ko : language.startsWith('ja') ? ja : language.startsWith('zh') ? zh : en; }
export function useGuideCopy(): GuideCopy { const { i18n } = useTranslation(); return getGuideCopy(i18n.resolvedLanguage ?? i18n.language); }
