import { StyleSheet } from 'react-native';
import type { ThemeColors } from './theme';

export function createStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.bg,
    },
    main: {
      flex: 1,
    },
    listHeader: {
      paddingBottom: 0,
    },
    homeHero: {
      paddingBottom: 12,
      backgroundColor: colors.heroBg,
    },
    listContent: {
      paddingBottom: 28,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingTop: 16,
      paddingBottom: 8,
    },
    headerText: {
      flex: 1,
      paddingRight: 8,
      justifyContent: 'flex-start',
      alignItems: 'flex-start',
    },
    logoWordmark: {
      width: 220,
      height: 82,
      backgroundColor: 'transparent',
      marginBottom: -6,
    },
    headerSubtitle: {
      marginLeft: 24,
      marginRight: 8,
      marginTop: 0,
      marginBottom: 0,
      fontSize: 15,
      lineHeight: 21,
      fontWeight: '600',
      letterSpacing: -0.2,
      color: colors.textSecondary,
    },
    emergencyFinderCard: {
      flexDirection: 'row',
      alignItems: 'center',
      marginHorizontal: 20,
      marginTop: 8,
      marginBottom: 4,
      paddingHorizontal: 14,
      paddingVertical: 13,
      borderRadius: 16,
      backgroundColor: colors.accentMuted,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.accentMuted,
    },
    emergencyFinderIcon: {
      width: 38,
      height: 38,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surface,
      marginRight: 12,
    },
    emergencyFinderEmoji: {
      fontSize: 18,
    },
    emergencyFinderText: {
      flex: 1,
      paddingRight: 8,
    },
    emergencyFinderTitle: {
      color: colors.textPrimary,
      fontSize: 15,
      fontWeight: '700',
      letterSpacing: -0.2,
    },
    emergencyFinderDescription: {
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 17,
      marginTop: 3,
    },

    requestOverlay: {
      flex: 1,
      justifyContent: 'flex-end',
    },
    requestBackdrop: {
      ...StyleSheet.absoluteFill,
      backgroundColor: colors.overlay,
    },
    requestSheet: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      maxHeight: '88%',
      paddingTop: 8,
    },
    requestScroll: {
      flexGrow: 0,
    },
    requestScrollContent: {
      paddingHorizontal: 20,
      paddingBottom: 8,
    },
    requestTitle: {
      fontSize: 18,
      fontWeight: '700',
      letterSpacing: -0.3,
      color: colors.textPrimary,
      paddingHorizontal: 20,
      marginBottom: 4,
    },
    requestDesc: {
      fontSize: 13,
      lineHeight: 19,
      color: colors.textSecondary,
      paddingHorizontal: 20,
      marginBottom: 16,
    },
    requestField: {
      marginBottom: 14,
    },
    requestLabelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: 8,
    },
    requestLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    requestOptional: {
      fontSize: 11,
      fontWeight: '500',
      color: colors.textTertiary,
    },
    requestInput: {
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: 10,
      backgroundColor: colors.bg,
      color: colors.textPrimary,
      fontSize: 15,
    },
    requestTextarea: {
      minHeight: 96,
      paddingTop: 12,
    },
    requestError: {
      marginTop: 2,
      marginBottom: 4,
      fontSize: 13,
      lineHeight: 18,
      color: colors.accent,
    },
    requestFooter: {
      paddingHorizontal: 20,
      paddingTop: 12,
      paddingBottom: 28,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.divider,
      gap: 4,
    },
    requestSubmitBtn: {
      paddingVertical: 15,
      borderRadius: 10,
      alignItems: 'center',
      backgroundColor: colors.accent,
    },
    requestSubmitBtnPressed: {
      opacity: 0.9,
    },
    requestSubmitText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '700',
    },
    requestCancelLink: {
      paddingVertical: 10,
      alignItems: 'center',
    },
    requestCancelText: {
      fontSize: 14,
      fontWeight: '500',
      color: colors.textTertiary,
    },

    searchShell: {
      flexDirection: 'row',
      alignItems: 'center',
      marginHorizontal: 20,
      marginBottom: 12,
      minHeight: 52,
      paddingHorizontal: 17,
      gap: 10,
      borderRadius: 18,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.025,
      shadowRadius: 8,
      elevation: 1,
    },
    search: {
      flex: 1,
      paddingVertical: 10,
      color: colors.textPrimary,
      fontSize: 16,
      fontWeight: '600',
    },

    filterPanel: {
      marginBottom: 4,
    },
    situationScroll: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 9,
      paddingHorizontal: 20,
      paddingRight: 24,
    },
    situationChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 18,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    situationChipActive: {
      backgroundColor: colors.accentMuted,
    },
    situationChipFav: {
      backgroundColor: colors.accent,
      borderColor: colors.accent,
    },
    situationChipFavActive: {
      backgroundColor: colors.accent,
      borderColor: colors.accent,
    },
    situationIcon: {
      fontSize: 14,
    },
    situationChipText: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textPrimary,
    },
    situationChipTextActive: {
      color: colors.accent,
      fontWeight: '600',
    },
    situationChipFavTextActive: {
      color: '#fff',
      fontWeight: '600',
    },
    tipBanner: {
      marginTop: 12,
      marginHorizontal: 20,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 14,
      backgroundColor: colors.tipBg,
    },
    tipBannerText: {
      fontSize: 13,
      lineHeight: 18,
      color: colors.tipText,
    },

    categoryBrowse: {
      paddingBottom: 12,
      paddingTop: 4,
    },
    categoryBrowseSectionHeader: {
      marginHorizontal: 20,
      marginTop: 8,
      marginBottom: 12,
      flexDirection: 'row',
      alignItems: 'baseline',
      justifyContent: 'space-between',
    },
    categoryBrowseSectionHeaderSpaced: {
      marginTop: 22,
    },
    categoryBrowseSectionTitle: {
      fontSize: 19,
      fontWeight: '800',
      letterSpacing: -0.4,
      color: colors.textPrimary,
    },
    categoryBrowseMore: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    categoryGrid: {
      marginHorizontal: 20,
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    categoryTile: {
      width: '47.8%',
      flexGrow: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      minHeight: 76,
      paddingVertical: 12,
      paddingHorizontal: 12,
      borderRadius: 14,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    categoryTileIconWrap: {
      width: 36,
      height: 36,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    categoryTileText: {
      flex: 1,
      gap: 2,
      minWidth: 0,
    },
    categoryTileTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    categoryTileSubtitle: {
      fontSize: 11,
      lineHeight: 15,
      color: colors.textSecondary,
    },

    immediateEmergency: {
      marginTop: 8,
      marginBottom: 4,
      paddingHorizontal: 20,
    },
    immediateEmergencyTitle: {
      fontSize: 19,
      fontWeight: '800',
      letterSpacing: -0.4,
      color: colors.textPrimary,
      marginBottom: 12,
    },
    immediateEmergencyRow: {
      flexDirection: 'row',
      gap: 10,
    },
    immediateCard: {
      flex: 1,
      minWidth: 0,
      paddingVertical: 14,
      paddingHorizontal: 14,
      borderRadius: 16,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    immediateCardFire: {
      backgroundColor: colors.accentMuted,
      borderColor: colors.accentMuted,
    },
    immediateCardPolice: {},
    immediateCardTop: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 8,
    },
    immediateCardEmoji: {
      fontSize: 22,
      lineHeight: 26,
    },
    immediateCardNum: {
      fontSize: 26,
      fontWeight: '800',
      letterSpacing: -0.6,
    },
    immediateCardLabel: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.textPrimary,
      marginBottom: 3,
    },
    immediateCardDesc: {
      fontSize: 12,
      lineHeight: 16,
      color: colors.textSecondary,
    },

    situationMoreSheet: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      paddingHorizontal: 20,
      paddingTop: 12,
      paddingBottom: 28,
    },
    situationMoreHandle: {
      alignSelf: 'center',
      width: 36,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.divider,
      marginBottom: 14,
    },
    situationMoreTitle: {
      fontSize: 17,
      fontWeight: '700',
      color: colors.textPrimary,
      marginBottom: 12,
    },
    situationMoreRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.divider,
    },
    situationMoreRowText: {
      flex: 1,
      fontSize: 16,
      fontWeight: '600',
      color: colors.textPrimary,
    },
    categoryScreen: {
      flex: 1,
    },
    categoryScreenTopBar: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingTop: 4,
      paddingBottom: 10,
      minHeight: 48,
    },
    categoryScreenBack: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    categoryScreenTitleWrap: {
      flex: 1,
      alignItems: 'center',
    },
    categoryScreenTitle: {
      fontSize: 16,
      fontWeight: '700',
      textAlign: 'center',
      color: colors.textPrimary,
      includeFontPadding: false,
    },
    categoryScreenSubtitle: {
      marginTop: 2,
      fontSize: 12,
      color: colors.textSecondary,
      textAlign: 'center',
    },
    categoryScreenList: {
      paddingBottom: 28,
    },

    tabBar: {
      flexDirection: 'row',
      alignItems: 'stretch',
      backgroundColor: colors.surface,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
      paddingTop: 4,
      paddingHorizontal: 28,
    },
    tabItem: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 3,
      borderRadius: 18,
      gap: 2,
    },
    tabItemActive: {
      backgroundColor: colors.accentMuted,
    },
    tabLabel: {
      fontSize: 11,
      fontWeight: '600',
      color: colors.textTertiary,
    },
    tabLabelActive: {
      color: colors.accent,
    },

    moreScroll: {
      flex: 1,
    },
    moreContent: {
      paddingHorizontal: 20,
      paddingTop: 10,
      paddingBottom: 88,
    },
    moreHero: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 20,
    },
    moreHeroText: {
      flex: 1,
      paddingRight: 8,
    },
    moreHeroGraphic: {
      width: 86,
      height: 86,
      marginRight: -4,
    },
    moreTitle: {
      fontSize: 34,
      fontWeight: '800',
      letterSpacing: -1.1,
      color: colors.textPrimary,
    },
    moreSubtitle: {
      marginTop: 4,
      marginBottom: 0,
      fontSize: 16,
      lineHeight: 23,
      color: colors.textSecondary,
    },
    moreSection: {
      marginBottom: 20,
      borderRadius: 20,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      overflow: 'hidden',
    },
    moreSectionLabel: {
      marginBottom: 10,
      marginLeft: 4,
      fontSize: 15,
      fontWeight: '700',
      color: colors.textSecondary,
    },
    moreRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 13,
      paddingHorizontal: 18,
      paddingVertical: 13,
    },
    moreLinkRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 13,
      paddingHorizontal: 18,
      paddingVertical: 14,
    },
    moreRowIcon: {
      width: 46,
      height: 46,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 15,
      backgroundColor: colors.accentMuted,
    },
    moreRowText: {
      flex: 1,
      minWidth: 0,
    },
    moreRowTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    moreRowHint: {
      marginTop: 2,
      fontSize: 13,
      lineHeight: 19,
      color: colors.textTertiary,
    },
    moreRowDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.divider,
      marginLeft: 77,
    },
    moreChevron: {
      fontSize: 20,
      color: colors.textTertiary,
      lineHeight: 22,
    },
    moreMeta: {
      marginTop: 26,
      textAlign: 'center',
      fontSize: 12,
      lineHeight: 20,
      color: colors.textTertiary,
    },
    feedbackCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 13,
      paddingHorizontal: 18,
      paddingVertical: 18,
      borderRadius: 20,
      backgroundColor: colors.accentMuted,
    },
    feedbackTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    feedbackHint: {
      marginTop: 3,
      fontSize: 13,
      color: colors.textSecondary,
    },

    privacyWrap: {
      flex: 1,
    },
    privacyTopBar: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingBottom: 10,
      minHeight: 44,
    },
    privacyBackBtn: {
      minWidth: 64,
      paddingVertical: 6,
      paddingHorizontal: 8,
    },
    privacyBackText: {
      fontSize: 16,
      fontWeight: '500',
    },
    privacyTopTitle: {
      flex: 1,
      textAlign: 'center',
      fontSize: 16,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    privacyTopSpacer: {
      minWidth: 64,
    },
    privacyScroll: {
      flex: 1,
    },
    privacyContent: {
      paddingHorizontal: 20,
      paddingBottom: 40,
    },
    privacyLead: {
      fontSize: 15,
      lineHeight: 23,
      color: colors.textSecondary,
      marginBottom: 24,
    },
    privacySection: {
      marginBottom: 22,
      gap: 8,
    },
    privacySectionTitle: {
      fontSize: 16,
      fontWeight: '700',
      letterSpacing: -0.2,
      color: colors.textPrimary,
      marginBottom: 2,
    },
    privacyBody: {
      flex: 1,
      fontSize: 14,
      lineHeight: 22,
      color: colors.textSecondary,
    },
    privacyBulletRow: {
      flexDirection: 'row',
      gap: 6,
      paddingLeft: 2,
    },
    privacyBulletMark: {
      fontSize: 14,
      lineHeight: 22,
      color: colors.textTertiary,
      width: 10,
    },
    privacyLink: {
      fontSize: 14,
      lineHeight: 22,
      fontWeight: '600',
      color: colors.accent,
    },
    privacyUpdated: {
      marginTop: 4,
      fontSize: 13,
      lineHeight: 19,
      color: colors.textTertiary,
    },

    sectionHeader: {
      marginHorizontal: 20,
      marginTop: 18,
      marginBottom: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    sectionHeaderPressable: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    sectionChevron: {
      color: colors.textTertiary,
    },
    sectionItem: {
      marginHorizontal: 20,
      backgroundColor: colors.surface,
      borderLeftWidth: StyleSheet.hairlineWidth,
      borderRightWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    sectionItemFirst: {
      borderTopLeftRadius: 12,
      borderTopRightRadius: 12,
      borderTopWidth: StyleSheet.hairlineWidth,
      overflow: 'hidden',
    },
    sectionItemLast: {
      borderBottomLeftRadius: 12,
      borderBottomRightRadius: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      overflow: 'hidden',
      marginBottom: 0,
    },
    cardDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.divider,
      marginLeft: 56,
    },
    catHeader: {
      fontSize: 20,
      fontWeight: '800',
      letterSpacing: -0.5,
      color: colors.textPrimary,
    },
    catSubtitle: {
      marginTop: 2,
      fontSize: 13,
      lineHeight: 18,
      color: colors.textSecondary,
    },
    catHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    catHeaderText: {
      flex: 1,
      minWidth: 0,
    },
    favHeader: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    favHeaderStar: {
      color: colors.favorite,
    },

    card: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingVertical: 16,
      paddingHorizontal: 16,
    },
    iconWrap: {
      width: 44,
      height: 44,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    icon: {
      fontSize: 20,
    },
    iconLg: {
      fontSize: 26,
    },
    cardBody: {
      flex: 1,
      minWidth: 0,
    },
    cardTitle: {
      fontSize: 15,
      fontWeight: '600',
      letterSpacing: -0.2,
      color: colors.textPrimary,
    },
    cardDesc: {
      marginTop: 2,
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 17,
    },
    cardActions: {
      alignItems: 'flex-end',
      gap: 6,
      paddingLeft: 4,
    },
    cardDragging: {
      opacity: 0.92,
    },
    dragHandle: {
      paddingVertical: 2,
      paddingHorizontal: 2,
    },
    dragHandleIcon: {
      color: colors.textTertiary,
    },
    favReorderHint: {
      marginHorizontal: 20,
      marginBottom: 8,
      fontSize: 12,
      lineHeight: 16,
      color: colors.textTertiary,
    },
    favorite: {
      fontSize: 16,
      color: colors.textTertiary,
    },
    favoriteActive: {
      color: colors.favorite,
    },
    callBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 10,
      backgroundColor: colors.accentMuted,
    },
    callText: {
      fontSize: 14,
      fontWeight: '700',
      letterSpacing: -0.3,
      color: colors.accent,
    },

    gridRow: {
      flexDirection: 'row',
      gap: 10,
      marginHorizontal: 20,
      marginBottom: 10,
    },
    gridCell: {
      flex: 1,
      minWidth: 0,
    },
    gridCellSpacer: {
      flex: 1,
    },
    gridCard: {
      flex: 1,
      paddingHorizontal: 12,
      paddingTop: 12,
      paddingBottom: 12,
      borderRadius: 16,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    gridCardTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    gridIconWrap: {
      width: 36,
      height: 36,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    gridIcon: {
      fontSize: 18,
    },
    gridCardTitle: {
      fontSize: 14,
      fontWeight: '700',
      letterSpacing: -0.3,
      color: colors.textPrimary,
      lineHeight: 19,
      marginBottom: 3,
      minHeight: 38,
    },
    gridCardDesc: {
      fontSize: 12,
      lineHeight: 16,
      color: colors.textTertiary,
      marginBottom: 10,
    },
    gridCallBtn: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 4,
      alignSelf: 'stretch',
      paddingVertical: 8,
      borderRadius: 10,
      backgroundColor: colors.accentMuted,
    },
    gridCallText: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.accent,
    },
    cardModeHeader: {
      marginHorizontal: 20,
      marginTop: 14,
      marginBottom: 10,
    },
    cardModeHeaderPressable: {
      flex: 1,
    },

    emptyWrap: {
      marginHorizontal: 20,
      marginTop: 40,
      alignItems: 'center',
    },
    empty: {
      textAlign: 'center',
      color: colors.textTertiary,
      fontSize: 14,
    },
    emptyIcon: {
      fontSize: 28,
      color: colors.textTertiary,
      marginBottom: 8,
    },
    emptyTitle: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.textPrimary,
      marginBottom: 6,
    },
    emptyHint: {
      fontSize: 13,
      lineHeight: 19,
      color: colors.textTertiary,
      textAlign: 'center',
    },

    overlay: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: colors.overlay,
    },
    sheet: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      paddingHorizontal: 20,
      paddingBottom: 20,
      paddingTop: 8,
      maxHeight: '88%',
    },
    handle: {
      alignSelf: 'center',
      width: 36,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.divider,
      marginBottom: 14,
    },
    sheetScroll: {
      flexGrow: 0,
    },
    sheetScrollContent: {
      paddingBottom: 8,
    },
    sheetHeader: {
      flexDirection: 'row',
      gap: 14,
      marginBottom: 12,
    },
    sheetHeaderText: {
      flex: 1,
    },
    sheetCat: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.textTertiary,
      marginBottom: 2,
    },
    sheetTitle: {
      fontSize: 20,
      fontWeight: '700',
      letterSpacing: -0.4,
      color: colors.textPrimary,
    },
    sheetDesc: {
      marginTop: 6,
      fontSize: 14,
      color: colors.textSecondary,
      lineHeight: 20,
    },
    sheetNumber: {
      marginBottom: 14,
      fontSize: 28,
      fontWeight: '800',
      letterSpacing: -0.6,
      color: colors.accent,
    },
    sheetDetail: {
      marginBottom: 10,
      fontSize: 14,
      lineHeight: 22,
      color: colors.textSecondary,
    },
    tipBox: {
      marginTop: 4,
      marginBottom: 8,
      padding: 12,
      borderRadius: 10,
      backgroundColor: colors.tipBg,
    },
    tipText: {
      color: colors.tipText,
      fontSize: 14,
      lineHeight: 20,
    },
    sheetActions: {
      gap: 8,
      paddingTop: 12,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.divider,
    },
    secondaryBtn: {
      paddingVertical: 14,
      borderRadius: 10,
      alignItems: 'center',
      backgroundColor: colors.bg,
    },
    secondaryBtnText: {
      color: colors.textPrimary,
      fontSize: 15,
      fontWeight: '600',
    },
    primaryBtn: {
      paddingVertical: 16,
      borderRadius: 10,
      alignItems: 'center',
      backgroundColor: colors.accent,
    },
    primaryBtnText: {
      color: '#fff',
      fontSize: 17,
      fontWeight: '700',
      letterSpacing: -0.3,
    },

    toastWrap: {
      position: 'absolute',
      left: 20,
      right: 20,
      zIndex: 100,
      alignItems: 'center',
    },
    toast: {
      maxWidth: '100%',
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderRadius: 12,
      backgroundColor: colors.textPrimary,
    },
    toastText: {
      color: colors.bg,
      fontSize: 14,
      fontWeight: '600',
      textAlign: 'center',
      letterSpacing: -0.2,
    },
  });
}

export type AppStyles = ReturnType<typeof createStyles>;
