import { StyleSheet } from 'react-native';
import type { ThemeColors } from './theme';

export function createStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.bg,
    },
    listHeader: {
      paddingBottom: 4,
    },
    listContent: {
      paddingBottom: 24,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 12,
    },
    headerText: {
      flex: 1,
      paddingRight: 12,
    },
    logo: {
      fontSize: 24,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    subtitle: {
      marginTop: 4,
      fontSize: 14,
      color: colors.textSecondary,
    },
    requestTrigger: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginHorizontal: 16,
      marginBottom: 10,
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: 14,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    requestTriggerPressed: {
      opacity: 0.92,
    },
    requestTriggerIcon: {
      width: 32,
      height: 32,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: `${colors.accent}18`,
    },
    requestTriggerIconText: {
      fontSize: 18,
      fontWeight: '600',
      color: colors.accent,
      lineHeight: 20,
    },
    requestTriggerBody: {
      flex: 1,
      minWidth: 0,
    },
    requestTriggerLabel: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.textPrimary,
    },
    requestTriggerSub: {
      marginTop: 2,
      fontSize: 12,
      color: colors.textTertiary,
    },
    requestTriggerChevron: {
      fontSize: 22,
      fontWeight: '300',
      color: colors.textTertiary,
      lineHeight: 24,
    },
    requestOverlay: {
      flex: 1,
      justifyContent: 'flex-end',
    },
    requestBackdrop: {
      ...StyleSheet.absoluteFill,
      backgroundColor: colors.overlay,
    },
    requestSheet: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: 22,
      borderTopRightRadius: 22,
      borderWidth: 1,
      borderBottomWidth: 0,
      borderColor: colors.border,
      maxHeight: '88%',
      paddingTop: 8,
    },
    requestScroll: {
      flexGrow: 0,
    },
    requestScrollContent: {
      paddingHorizontal: 20,
      paddingBottom: 8,
    },
    requestTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.textPrimary,
      paddingHorizontal: 20,
      marginBottom: 4,
    },
    requestDesc: {
      fontSize: 13,
      lineHeight: 19,
      color: colors.textSecondary,
      paddingHorizontal: 20,
      marginBottom: 16,
    },
    requestField: {
      marginBottom: 14,
    },
    requestLabelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: 8,
    },
    requestLabel: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.textSecondary,
      letterSpacing: 0.2,
    },
    requestOptional: {
      fontSize: 11,
      fontWeight: '500',
      color: colors.textTertiary,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 999,
      backgroundColor: colors.bg,
    },
    requestInput: {
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: 12,
      backgroundColor: colors.bg,
      borderWidth: 1,
      borderColor: colors.border,
      color: colors.textPrimary,
      fontSize: 15,
    },
    requestTextarea: {
      minHeight: 96,
      paddingTop: 12,
    },
    requestError: {
      marginTop: 2,
      marginBottom: 4,
      fontSize: 13,
      lineHeight: 18,
      color: '#d94f3d',
    },
    requestFooter: {
      paddingHorizontal: 20,
      paddingTop: 12,
      paddingBottom: 28,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      gap: 4,
    },
    requestSubmitBtn: {
      paddingVertical: 15,
      borderRadius: 12,
      alignItems: 'center',
      backgroundColor: colors.accent,
    },
    requestSubmitBtnPressed: {
      opacity: 0.9,
    },
    requestSubmitText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '700',
    },
    requestCancelLink: {
      paddingVertical: 10,
      alignItems: 'center',
    },
    requestCancelText: {
      fontSize: 14,
      fontWeight: '500',
      color: colors.textTertiary,
    },
    search: {
      marginHorizontal: 16,
      marginBottom: 8,
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: 12,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      color: colors.textPrimary,
      fontSize: 16,
    },
    filterPanel: {
      marginHorizontal: 16,
      marginBottom: 8,
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderRadius: 14,
      backgroundColor: colors.surface,
    },
    filterDisabled: {
      opacity: 0.45,
    },
    categoryPanel: {
      paddingVertical: 12,
    },
    filterLabel: {
      marginBottom: 10,
      fontSize: 11,
      fontWeight: '600',
      letterSpacing: 0.6,
      textTransform: 'uppercase',
      color: colors.textTertiary,
    },
    situationGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      rowGap: 8,
    },
    situationBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      width: '48%',
      paddingHorizontal: 12,
      paddingVertical: 9,
      borderRadius: 10,
      backgroundColor: colors.bg,
      borderWidth: 1,
      borderColor: colors.border,
    },
    situationIcon: {
      fontSize: 15,
    },
    situationLabel: {
      flex: 1,
      fontSize: 13,
      color: colors.textPrimary,
      lineHeight: 18,
    },
    tipBanner: {
      marginTop: 10,
      padding: 10,
      borderRadius: 10,
      backgroundColor: colors.tipBg,
      borderWidth: 1,
      borderColor: colors.tipBorder,
    },
    tipBannerText: {
      fontSize: 13,
      lineHeight: 19,
      color: colors.tipText,
    },
    categoryScroll: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingRight: 4,
    },
    categoryChip: {
      paddingHorizontal: 14,
      paddingVertical: 5,
      borderRadius: 999,
      backgroundColor: colors.bg,
      borderWidth: 1,
      borderColor: colors.border,
    },
    categoryChipFav: {
      borderColor: 'rgba(245, 158, 11, 0.45)',
    },
    categoryChipActive: {
      backgroundColor: colors.textPrimary,
      borderColor: colors.textPrimary,
    },
    categoryChipFavActive: {
      backgroundColor: colors.favorite,
      borderColor: colors.favorite,
    },
    categoryChipText: {
      fontSize: 12,
      fontWeight: '500',
      color: colors.textPrimary,
    },
    categoryChipTextActive: {
      color: colors.chipActiveText,
    },
    categoryChipFavTextActive: {
      color: '#fff',
    },
    sectionGap: {
      height: 10,
    },
    sectionHeader: {
      marginHorizontal: 16,
      paddingHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 8,
      backgroundColor: colors.surface,
      borderTopLeftRadius: 14,
      borderTopRightRadius: 14,
    },
    sectionItem: {
      marginHorizontal: 16,
      paddingHorizontal: 16,
      backgroundColor: colors.surface,
    },
    sectionItemFirst: {
      borderTopLeftRadius: 14,
      borderTopRightRadius: 14,
      paddingTop: 4,
    },
    sectionItemLast: {
      paddingBottom: 16,
      borderBottomLeftRadius: 14,
      borderBottomRightRadius: 14,
    },
    cardDivider: {
      height: 8,
    },
    catHeader: {
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.6,
      textTransform: 'uppercase',
    },
    favHeader: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    favHeaderStar: {
      color: colors.favorite,
    },
    card: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingVertical: 8,
    },
    iconWrap: {
      width: 44,
      height: 44,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    icon: {
      fontSize: 22,
    },
    iconLg: {
      fontSize: 28,
    },
    cardBody: {
      flex: 1,
      minWidth: 0,
    },
    cardTitle: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.textPrimary,
    },
    cardDesc: {
      marginTop: 2,
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 18,
    },
    cardActions: {
      alignItems: 'flex-end',
      gap: 8,
    },
    favorite: {
      fontSize: 18,
      color: colors.textTertiary,
    },
    favoriteActive: {
      color: colors.favorite,
    },
    callBtn: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 8,
      backgroundColor: 'rgba(59, 111, 212, 0.15)',
    },
    callText: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.accent,
    },
    emptyWrap: {
      marginHorizontal: 16,
      marginTop: 32,
      alignItems: 'center',
    },
    empty: {
      textAlign: 'center',
      color: colors.textTertiary,
      fontSize: 14,
    },
    emptyIcon: {
      fontSize: 32,
      color: colors.textTertiary,
      marginBottom: 8,
    },
    emptyTitle: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.textPrimary,
      marginBottom: 6,
    },
    emptyHint: {
      fontSize: 13,
      lineHeight: 19,
      color: colors.textTertiary,
      textAlign: 'center',
    },
    overlay: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: colors.overlay,
    },
    sheet: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      paddingHorizontal: 20,
      paddingBottom: 32,
      paddingTop: 8,
      borderWidth: 1,
      borderColor: colors.border,
    },
    handle: {
      alignSelf: 'center',
      width: 36,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.border,
      marginBottom: 16,
    },
    sheetHeader: {
      flexDirection: 'row',
      gap: 14,
      marginBottom: 16,
    },
    sheetHeaderText: {
      flex: 1,
    },
    sheetTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    sheetDesc: {
      marginTop: 6,
      fontSize: 15,
      color: colors.textSecondary,
      lineHeight: 22,
    },
    tipBox: {
      marginBottom: 16,
      padding: 14,
      borderRadius: 12,
      backgroundColor: colors.tipBg,
      borderWidth: 1,
      borderColor: colors.tipBorder,
    },
    tipText: {
      color: colors.tipText,
      fontSize: 14,
      lineHeight: 20,
    },
    sheetActions: {
      gap: 10,
    },
    secondaryBtn: {
      paddingVertical: 14,
      borderRadius: 12,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
    },
    secondaryBtnText: {
      color: colors.textPrimary,
      fontSize: 16,
      fontWeight: '600',
    },
    primaryBtn: {
      paddingVertical: 16,
      borderRadius: 12,
      alignItems: 'center',
      backgroundColor: colors.accent,
    },
    primaryBtnText: {
      color: '#fff',
      fontSize: 17,
      fontWeight: '700',
    },
  });
}

export type AppStyles = ReturnType<typeof createStyles>;
