import type { OrganizationContact } from './numbers';

/**
 * 공공 긴급번호와 구분해 관리하는 기업 긴급 연락처입니다.
 * 번호는 각 기관의 공식 고객센터/사고신고 페이지로만 확인해 수록합니다.
 */
export const ORGANIZATION_CONTACTS: OrganizationContact[] = [
  {
    id: 'org-ins-samsung-auto',
    cat: '교통/차량',
    icon: '🚗',
    title: '삼성화재 자동차 사고·긴급출동',
    desc: '사고접수·고장출동 ARS',
    num: '1588-5114',
    situation: ['car'],
    tip: 'ARS 1번은 자동차 사고접수, 2번은 자동차 고장출동 요청입니다.',
    organization: '삼성화재',
    organizationType: 'insurance',
    purpose: 'accident',
    keywords: [
      '자동차 사고',
      '차 사고',
      '교통사고',
      '차 고장',
      '긴급출동',
      '견인',
      '배터리 방전',
      '타이어 펑크',
      '보험 사고접수',
    ],
    available24h: true,
    source: 'https://direct.samsungfire.com/index.html?pcfront=',
    verifiedAt: '2026-09-13',
  },
  {
    id: 'org-ins-db-auto',
    cat: '교통/차량',
    icon: '🚗',
    title: 'DB손해보험 사고·긴급출동',
    desc: '자동차 사고접수·고장출동',
    num: '1588-0100',
    situation: ['car'],
    organization: 'DB손해보험',
    organizationType: 'insurance',
    purpose: 'accident',
    keywords: [
      '자동차 사고',
      '차 사고',
      '교통사고',
      '차 고장',
      '긴급출동',
      '견인',
      '배터리 방전',
      '타이어 펑크',
      '보험 사고접수',
    ],
    available24h: true,
    source: 'https://www.directdb.co.kr/mainView.do?cmd=main',
    verifiedAt: '2026-09-13',
  },
  {
    id: 'org-ins-kb-auto',
    cat: '교통/차량',
    icon: '🚗',
    title: 'KB손해보험 사고·긴급출동',
    desc: '자동차 사고접수·고장출동',
    num: '1544-0114',
    situation: ['car'],
    organization: 'KB손해보험',
    organizationType: 'insurance',
    purpose: 'accident',
    keywords: [
      '자동차 사고',
      '차 사고',
      '교통사고',
      '차 고장',
      '긴급출동',
      '견인',
      '배터리 방전',
      '타이어 펑크',
      '보험 사고접수',
    ],
    available24h: true,
    source: 'https://direct.kbinsure.co.kr/',
    verifiedAt: '2026-09-13',
  },
  {
    id: 'org-ins-hyundai-auto',
    cat: '교통/차량',
    icon: '🚗',
    title: '현대해상 자동차 사고·긴급출동',
    desc: '사고접수·고장출동 ARS',
    num: '1588-5656',
    situation: ['car'],
    tip: 'ARS 1번은 고장출동, 2번은 사고접수입니다.',
    organization: '현대해상',
    organizationType: 'insurance',
    purpose: 'accident',
    keywords: [
      '현대해상',
      '자동차 사고',
      '차 사고',
      '교통사고',
      '차 고장',
      '긴급출동',
      '견인',
      '배터리 방전',
      '타이어 펑크',
      '보험 사고접수',
    ],
    available24h: true,
    source: 'https://cardirect-direct.hi.co.kr/service.do?m=483ee197fc',
    verifiedAt: '2026-09-23',
  },
  {
    id: 'org-ins-meritz-auto',
    cat: '교통/차량',
    icon: '🚗',
    title: '메리츠화재 자동차 사고·긴급출동',
    desc: '사고접수·긴급출동',
    num: '1566-7711',
    situation: ['car'],
    organization: '메리츠화재',
    organizationType: 'insurance',
    purpose: 'accident',
    keywords: [
      '메리츠화재',
      '메리츠',
      '자동차 사고',
      '차 사고',
      '교통사고',
      '차 고장',
      '긴급출동',
      '견인',
      '배터리 방전',
      '타이어 펑크',
      '보험 사고접수',
    ],
    available24h: true,
    source: 'https://store.meritzfire.com/main.do',
    verifiedAt: '2026-09-23',
  },
  {
    id: 'org-ins-hanwha-auto',
    cat: '교통/차량',
    icon: '🚗',
    title: '한화손해보험 사고·긴급출동',
    desc: '사고접수·고장출동',
    num: '1566-8000',
    situation: ['car'],
    tip: 'ARS에서 사고접수·긴급출동을 선택할 수 있어요.',
    organization: '한화손해보험',
    organizationType: 'insurance',
    purpose: 'accident',
    keywords: [
      '한화손해보험',
      '한화손보',
      '자동차 사고',
      '차 사고',
      '교통사고',
      '차 고장',
      '긴급출동',
      '견인',
      '배터리 방전',
      '타이어 펑크',
      '보험 사고접수',
    ],
    available24h: true,
    source: 'https://www.hwgeneralins.com/',
    verifiedAt: '2026-09-23',
  },
  {
    id: 'org-ins-lotte-auto',
    cat: '교통/차량',
    icon: '🚗',
    title: '롯데손해보험 사고·긴급출동',
    desc: '사고접수·고장출동 24시간',
    num: '1588-3344',
    situation: ['car'],
    tip: 'ARS 1번은 고장출동, 2번은 사고접수입니다.',
    organization: '롯데손해보험',
    organizationType: 'insurance',
    purpose: 'accident',
    keywords: [
      '롯데손해보험',
      '롯데손보',
      '자동차 사고',
      '차 사고',
      '교통사고',
      '차 고장',
      '긴급출동',
      '견인',
      '배터리 방전',
      '타이어 펑크',
      '보험 사고접수',
    ],
    available24h: true,
    source: 'https://www.lotteins.co.kr/web/C/D/I/popcdi010_ars.jsp',
    verifiedAt: '2026-09-23',
  },
  {
    id: 'org-ins-heungkuk-auto',
    cat: '교통/차량',
    icon: '🚗',
    title: '흥국화재 자동차 사고·긴급출동',
    desc: '사고접수·고장출동 24시간',
    num: '1688-1688',
    situation: ['car'],
    tip: 'ARS 1번은 사고접수, 2번은 고장 긴급출동입니다.',
    organization: '흥국화재',
    organizationType: 'insurance',
    purpose: 'accident',
    keywords: [
      '흥국화재',
      '자동차 사고',
      '차 사고',
      '교통사고',
      '차 고장',
      '긴급출동',
      '견인',
      '배터리 방전',
      '타이어 펑크',
      '보험 사고접수',
    ],
    available24h: true,
    source: 'https://m.heungkukfire.co.kr/servicecenter/uinf/CCSIN0301_M01/CCSIN0301_M01.do',
    verifiedAt: '2026-09-23',
  },
  {
    id: 'org-ins-mg-auto',
    cat: '교통/차량',
    icon: '🚗',
    title: 'MG손해보험 사고·긴급출동',
    desc: '자동차 사고접수·긴급출동',
    num: '1588-5959',
    situation: ['car'],
    organization: 'MG손해보험',
    organizationType: 'insurance',
    purpose: 'accident',
    keywords: [
      'MG손해보험',
      'MG손보',
      '자동차 사고',
      '차 사고',
      '교통사고',
      '차 고장',
      '긴급출동',
      '견인',
      '배터리 방전',
      '타이어 펑크',
      '보험 사고접수',
    ],
    available24h: true,
    source: 'https://carinfo.knia.or.kr/lmxsrv/cnswc/icnyCnswcList.do',
    verifiedAt: '2026-09-23',
  },
  {
    id: 'org-ins-axa-auto',
    cat: '교통/차량',
    icon: '🚗',
    title: 'AXA손해보험 사고·긴급출동',
    desc: '사고접수·고장출동 24시간',
    num: '1566-1566',
    situation: ['car'],
    tip: 'ARS 2번은 고장출동, 3번은 사고접수입니다.',
    organization: 'AXA손해보험',
    organizationType: 'insurance',
    purpose: 'accident',
    keywords: [
      'AXA손해보험',
      'AXA',
      '악사',
      '자동차 사고',
      '차 사고',
      '교통사고',
      '차 고장',
      '긴급출동',
      '견인',
      '배터리 방전',
      '타이어 펑크',
      '보험 사고접수',
    ],
    available24h: true,
    source: 'https://www.axa.co.kr/cms/benefit/cyms0304/cyms030401/CMKBEI01M01_CMS001.html',
    verifiedAt: '2026-09-23',
  },
  {
    id: 'org-ins-hana-auto',
    cat: '교통/차량',
    icon: '🚗',
    title: '하나손해보험 사고·긴급출동',
    desc: '사고접수·고장출동 24시간',
    num: '1566-3000',
    situation: ['car'],
    tip: 'ARS 1번은 고장출동, 2번은 사고접수입니다.',
    organization: '하나손해보험',
    organizationType: 'insurance',
    purpose: 'accident',
    keywords: [
      '하나손해보험',
      '하나손보',
      '자동차 사고',
      '차 사고',
      '교통사고',
      '차 고장',
      '긴급출동',
      '견인',
      '배터리 방전',
      '타이어 펑크',
      '보험 사고접수',
    ],
    available24h: true,
    source: 'https://www.hanainsure.co.kr/w/customer/homepageInfo/customerWork',
    verifiedAt: '2026-09-23',
  },
  {
    id: 'org-ins-carrot-auto',
    cat: '교통/차량',
    icon: '🚗',
    title: '캐롯손해보험 사고·긴급출동',
    desc: '자동차 사고접수·긴급출동',
    num: '1566-0300',
    situation: ['car'],
    organization: '캐롯손해보험',
    organizationType: 'insurance',
    purpose: 'accident',
    keywords: [
      '캐롯손해보험',
      '캐롯',
      '자동차 사고',
      '차 사고',
      '교통사고',
      '차 고장',
      '긴급출동',
      '견인',
      '배터리 방전',
      '타이어 펑크',
      '보험 사고접수',
    ],
    available24h: true,
    source: 'https://carinfo.knia.or.kr/lmxsrv/cnswc/icnyCnswcList.do',
    verifiedAt: '2026-09-23',
  },
  {
    id: 'org-card-hyundai-lost',
    cat: '법률/금융',
    icon: '💳',
    title: '현대카드 도난·분실 신고',
    desc: '카드 분실·도난·보이스피싱',
    num: '1577-6200',
    situation: ['crime', 'legal'],
    organization: '현대카드',
    organizationType: 'card',
    purpose: 'lost',
    keywords: [
      '카드 잃어버림',
      '카드 잃어버렸어',
      '카드 분실',
      '신용카드 분실',
      '카드 도난',
      '지갑 잃어버림',
      '해외 카드 분실',
      '카드 정지',
      '보이스피싱',
    ],
    available24h: true,
    source: 'https://mycompany.hyundaicard.com/cs/cl/CSCL1003.do?_method=l',
    verifiedAt: '2026-09-13',
  },
  {
    id: 'org-card-samsung-lost',
    cat: '법률/금융',
    icon: '💳',
    title: '삼성카드 분실·한도승인',
    desc: '카드 분실·금융사고 신고',
    num: '1588-8900',
    situation: ['crime', 'legal'],
    organization: '삼성카드',
    organizationType: 'card',
    purpose: 'lost',
    keywords: [
      '카드 잃어버림',
      '카드 잃어버렸어',
      '카드 분실',
      '신용카드 분실',
      '카드 도난',
      '지갑 잃어버림',
      '해외 카드 분실',
      '카드 정지',
      '보이스피싱',
    ],
    available24h: true,
    source: 'https://www.samsungcard.com/',
    verifiedAt: '2026-09-13',
  },
  {
    id: 'org-card-lotte-lost',
    cat: '법률/금융',
    icon: '💳',
    title: '롯데카드 분실·한도승인',
    desc: '카드 분실·도난 신고',
    num: '1588-8300',
    situation: ['crime', 'legal'],
    organization: '롯데카드',
    organizationType: 'card',
    purpose: 'lost',
    keywords: [
      '카드 잃어버림',
      '카드 잃어버렸어',
      '카드 분실',
      '신용카드 분실',
      '카드 도난',
      '지갑 잃어버림',
      '해외 카드 분실',
      '카드 정지',
    ],
    available24h: true,
    source: 'https://mweb2.lottecard.co.kr/app/LPCSTEA_V100.lc',
    verifiedAt: '2026-09-13',
  },
  {
    id: 'org-card-shinhan-lost',
    cat: '법률/금융',
    icon: '💳',
    title: '신한카드 분실·도난 신고',
    desc: '카드 분실·도난·승인 신고',
    num: '1544-7200',
    situation: ['crime', 'legal'],
    organization: '신한카드',
    organizationType: 'card',
    purpose: 'lost',
    keywords: [
      '신한카드',
      '카드 잃어버림',
      '카드 잃어버렸어',
      '카드 분실',
      '신용카드 분실',
      '카드 도난',
      '지갑 잃어버림',
      '해외 카드 분실',
      '카드 정지',
      '보이스피싱',
    ],
    available24h: true,
    source: 'https://www.shinhancard.com/conts/store/customor_center/ars_gu/cardLost.jsp',
    verifiedAt: '2026-09-23',
  },
  {
    id: 'org-card-kb-lost',
    cat: '법률/금융',
    icon: '💳',
    title: 'KB국민카드 분실·가맹점승인',
    desc: '카드 분실·도난·가맹점 승인',
    num: '1588-1788',
    situation: ['crime', 'legal'],
    organization: 'KB국민카드',
    organizationType: 'card',
    purpose: 'lost',
    keywords: [
      'KB국민카드',
      '국민카드',
      '카드 잃어버림',
      '카드 잃어버렸어',
      '카드 분실',
      '신용카드 분실',
      '카드 도난',
      '지갑 잃어버림',
      '해외 카드 분실',
      '카드 정지',
      '보이스피싱',
    ],
    available24h: true,
    source: 'https://card.kbcard.com/SVC/DVIEW/HSEMCXCRSZZC0001',
    verifiedAt: '2026-09-23',
  },
  {
    id: 'org-card-woori-lost',
    cat: '법률/금융',
    icon: '💳',
    title: '우리카드 분실 신고',
    desc: '카드 분실·도난·보이스피싱',
    num: '1588-5300',
    situation: ['crime', 'legal'],
    organization: '우리카드',
    organizationType: 'card',
    purpose: 'lost',
    keywords: [
      '우리카드',
      '카드 잃어버림',
      '카드 잃어버렸어',
      '카드 분실',
      '신용카드 분실',
      '카드 도난',
      '지갑 잃어버림',
      '해외 카드 분실',
      '카드 정지',
      '보이스피싱',
    ],
    available24h: true,
    source: 'https://pc.wooricard.com/dcpc/yh1/cct/cct04/H1CCT204S06.do',
    verifiedAt: '2026-09-23',
  },
  {
    id: 'org-card-hana-lost',
    cat: '법률/금융',
    icon: '💳',
    title: '하나카드 분실·도난 신고',
    desc: '카드 분실·도난·부정사용',
    num: '1800-1111',
    situation: ['crime', 'legal'],
    tip: '분실·도난은 전용 번호 없이 고객센터(1800-1111)로 바로 신고해요.',
    organization: '하나카드',
    organizationType: 'card',
    purpose: 'lost',
    keywords: [
      '하나카드',
      '카드 잃어버림',
      '카드 잃어버렸어',
      '카드 분실',
      '신용카드 분실',
      '카드 도난',
      '지갑 잃어버림',
      '해외 카드 분실',
      '카드 정지',
      '보이스피싱',
    ],
    available24h: true,
    source: 'https://www.hanacard.co.kr/OSA10000000N.web?mID=OSA10000000N&schID=scd',
    verifiedAt: '2026-09-23',
  },
  {
    id: 'org-card-nh-lost',
    cat: '법률/금융',
    icon: '💳',
    title: 'NH농협카드 분실·도난 신고',
    desc: '카드 분실·도난 신고',
    num: '1644-4000',
    situation: ['crime', 'legal'],
    tip: 'ARS 연결 뒤 1-1번에서 분실신고할 수 있어요. 24시간 가능.',
    organization: 'NH농협카드',
    organizationType: 'card',
    purpose: 'lost',
    keywords: [
      'NH농협카드',
      '농협카드',
      '카드 잃어버림',
      '카드 잃어버렸어',
      '카드 분실',
      '신용카드 분실',
      '카드 도난',
      '지갑 잃어버림',
      '해외 카드 분실',
      '카드 정지',
      '보이스피싱',
    ],
    available24h: true,
    source: 'https://card.nonghyup.com/content/html/ip/ci/ipci1010c.html',
    verifiedAt: '2026-09-23',
  },
  {
    id: 'org-bank-kb-incident',
    cat: '법률/금융',
    icon: '🏦',
    title: 'KB국민은행 분실·사고 신고',
    desc: '통장·현금카드·OTP·KB카드',
    num: '1588-9999',
    situation: ['crime', 'legal'],
    tip: 'ARS 연결 뒤 * 버튼에서 카드·통장·OTP 분실신고를 선택할 수 있어요.',
    organization: 'KB국민은행',
    organizationType: 'bank',
    purpose: 'lost',
    keywords: [
      '통장 분실',
      '은행',
      '계좌',
      '현금카드 분실',
      '체크카드 분실',
      'OTP 분실',
      '보안카드 분실',
      '금융사기',
      '카드 정지',
    ],
    available24h: true,
    source: 'https://obank.kbstar.com/quics?page=C028064',
    verifiedAt: '2026-09-13',
  },
  {
    id: 'org-bank-woori-incident',
    cat: '법률/금융',
    icon: '🏦',
    title: '우리은행 분실·금융사기 신고',
    desc: '통장·현금카드·OTP·보이스피싱',
    num: '1588-5000',
    situation: ['crime', 'legal'],
    tip: 'ARS 연결 뒤 #-1은 보이스피싱, #-2-3은 통장·인감, #-2-5는 OTP 분실신고입니다.',
    organization: '우리은행',
    organizationType: 'bank',
    purpose: 'fraud',
    keywords: [
      '통장 분실',
      '은행',
      '계좌',
      '현금카드 분실',
      'OTP 분실',
      '보안카드 분실',
      '보이스피싱',
      '금융사기',
      '송금 잘못',
      '계좌 정지',
    ],
    available24h: true,
    source: 'https://spot.wooribank.com/pot/Dream?withyou=CQACR0001',
    verifiedAt: '2026-09-13',
  },
];
