import type { OrganizationContact } from './numbers';

/**
 * 공공 긴급번호와 구분해 관리하는 기업 긴급 연락처입니다.
 * 번호는 각 기관의 공식 고객센터/사고신고 페이지로만 확인해 수록합니다.
 */
export const ORGANIZATION_CONTACTS: OrganizationContact[] = [
  {
    id: 'org-ins-samsung-auto',
    cat: '교통/차량',
    icon: '🚗',
    title: '삼성화재 자동차 사고·긴급출동',
    desc: '사고접수·고장출동 ARS',
    num: '1588-5114',
    situation: ['car'],
    tip: 'ARS 1번은 자동차 사고접수, 2번은 자동차 고장출동 요청입니다.',
    organization: '삼성화재',
    organizationType: 'insurance',
    purpose: 'accident',
    keywords: [
      '자동차 사고',
      '차 사고',
      '교통사고',
      '차 고장',
      '긴급출동',
      '견인',
      '배터리 방전',
      '타이어 펑크',
      '보험 사고접수',
    ],
    available24h: true,
    source: 'https://direct.samsungfire.com/index.html?pcfront=',
    verifiedAt: '2026-09-13',
  },
  {
    id: 'org-ins-db-auto',
    cat: '교통/차량',
    icon: '🚗',
    title: 'DB손해보험 사고·긴급출동',
    desc: '자동차 사고접수·고장출동',
    num: '1588-0100',
    situation: ['car'],
    organization: 'DB손해보험',
    organizationType: 'insurance',
    purpose: 'accident',
    keywords: [
      '자동차 사고',
      '차 사고',
      '교통사고',
      '차 고장',
      '긴급출동',
      '견인',
      '배터리 방전',
      '타이어 펑크',
      '보험 사고접수',
    ],
    available24h: true,
    source: 'https://www.directdb.co.kr/mainView.do?cmd=main',
    verifiedAt: '2026-09-13',
  },
  {
    id: 'org-ins-kb-auto',
    cat: '교통/차량',
    icon: '🚗',
    title: 'KB손해보험 사고·긴급출동',
    desc: '자동차 사고접수·고장출동',
    num: '1544-0114',
    situation: ['car'],
    organization: 'KB손해보험',
    organizationType: 'insurance',
    purpose: 'accident',
    keywords: [
      '자동차 사고',
      '차 사고',
      '교통사고',
      '차 고장',
      '긴급출동',
      '견인',
      '배터리 방전',
      '타이어 펑크',
      '보험 사고접수',
    ],
    available24h: true,
    source: 'https://direct.kbinsure.co.kr/',
    verifiedAt: '2026-09-13',
  },
  {
    id: 'org-card-hyundai-lost',
    cat: '법률/금융',
    icon: '💳',
    title: '현대카드 도난·분실 신고',
    desc: '카드 분실·도난·보이스피싱',
    num: '1577-6200',
    situation: ['crime', 'legal'],
    organization: '현대카드',
    organizationType: 'card',
    purpose: 'lost',
    keywords: [
      '카드 잃어버림',
      '카드 잃어버렸어',
      '카드 분실',
      '신용카드 분실',
      '카드 도난',
      '지갑 잃어버림',
      '해외 카드 분실',
      '카드 정지',
      '보이스피싱',
    ],
    available24h: true,
    source: 'https://mycompany.hyundaicard.com/cs/cl/CSCL1003.do?_method=l',
    verifiedAt: '2026-09-13',
  },
  {
    id: 'org-card-samsung-lost',
    cat: '법률/금융',
    icon: '💳',
    title: '삼성카드 분실·한도승인',
    desc: '카드 분실·금융사고 신고',
    num: '1588-8900',
    situation: ['crime', 'legal'],
    organization: '삼성카드',
    organizationType: 'card',
    purpose: 'lost',
    keywords: [
      '카드 잃어버림',
      '카드 잃어버렸어',
      '카드 분실',
      '신용카드 분실',
      '카드 도난',
      '지갑 잃어버림',
      '해외 카드 분실',
      '카드 정지',
      '보이스피싱',
    ],
    available24h: true,
    source: 'https://www.samsungcard.com/',
    verifiedAt: '2026-09-13',
  },
  {
    id: 'org-card-lotte-lost',
    cat: '법률/금융',
    icon: '💳',
    title: '롯데카드 분실·한도승인',
    desc: '카드 분실·도난 신고',
    num: '1588-8300',
    situation: ['crime', 'legal'],
    organization: '롯데카드',
    organizationType: 'card',
    purpose: 'lost',
    keywords: [
      '카드 잃어버림',
      '카드 잃어버렸어',
      '카드 분실',
      '신용카드 분실',
      '카드 도난',
      '지갑 잃어버림',
      '해외 카드 분실',
      '카드 정지',
    ],
    available24h: true,
    source: 'https://mweb2.lottecard.co.kr/app/LPCSTEA_V100.lc',
    verifiedAt: '2026-09-13',
  },
  {
    id: 'org-bank-kb-incident',
    cat: '법률/금융',
    icon: '🏦',
    title: 'KB국민은행 분실·사고 신고',
    desc: '통장·현금카드·OTP·KB카드',
    num: '1588-9999',
    situation: ['crime', 'legal'],
    tip: 'ARS 연결 뒤 * 버튼에서 카드·통장·OTP 분실신고를 선택할 수 있어요.',
    organization: 'KB국민은행',
    organizationType: 'bank',
    purpose: 'lost',
    keywords: [
      '통장 분실',
      '은행',
      '계좌',
      '현금카드 분실',
      '체크카드 분실',
      'OTP 분실',
      '보안카드 분실',
      '금융사기',
      '카드 정지',
    ],
    available24h: true,
    source: 'https://obank.kbstar.com/quics?page=C028064',
    verifiedAt: '2026-09-13',
  },
  {
    id: 'org-bank-woori-incident',
    cat: '법률/금융',
    icon: '🏦',
    title: '우리은행 분실·금융사기 신고',
    desc: '통장·현금카드·OTP·보이스피싱',
    num: '1588-5000',
    situation: ['crime', 'legal'],
    tip: 'ARS 연결 뒤 #-1은 보이스피싱, #-2-3은 통장·인감, #-2-5는 OTP 분실신고입니다.',
    organization: '우리은행',
    organizationType: 'bank',
    purpose: 'fraud',
    keywords: [
      '통장 분실',
      '은행',
      '계좌',
      '현금카드 분실',
      'OTP 분실',
      '보안카드 분실',
      '보이스피싱',
      '금융사기',
      '송금 잘못',
      '계좌 정지',
    ],
    available24h: true,
    source: 'https://spot.wooribank.com/pot/Dream?withyou=CQACR0001',
    verifiedAt: '2026-09-13',
  },
];
